import type { Movement, Session } from '@app/contracts';

export const sessionOverviews: Readonly<Record<string, string>> = {
  'session-2026-10-07': '/media/session-2026-10-07.jpg',
};

export const movements: Movement[] = [
  {
    id: 'shoulder-taps',
    name: 'Shoulder Taps',
    imagePath: '/media/shoulder-taps.jpg',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'banded-pull-aparts',
    name: 'Banded Pull Aparts',
    imagePath: '/media/repdb/banded-pull-aparts.webp',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'single-arm-row',
    name: 'Single Arm Row',
    imagePath: '/media/repdb/single-arm-row.webp',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'v-ups',
    name: 'V-Ups',
    imagePath: '/media/repdb/v-ups.webp',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'triple-extension',
    name: 'Triple Extension',
    imagePath: '/media/prep/triple-extension.jpg',
    videoPath: null,
    cues: 'Triple extension of the ankle, knees, and hips followed by a shoulder shrug',
    execution: '',
  },
  {
    id: 'ascending-scarecrow-pull',
    name: 'Ascending Scarecrow Pull',
    imagePath: '/media/prep/ascending-scarecrow-pull.jpg',
    videoPath: null,
    cues: 'Triple extension + object reaching chest level. Start small and increase height as the movement gets stronger.',
    execution: '',
  },
  {
    id: 'muscle-clean',
    name: 'Muscle Clean',
    imagePath: '/media/prep/muscle-clean.jpg',
    videoPath: null,
    cues: 'Everything we’ve learned put together.',
    execution: '',
  },
  {
    id: 'single-arm-muscle-clean',
    name: 'Single Arm Muscle Clean',
    imagePath: '/media/single-arm-muscle-clean.jpg',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'single-arm-push-press',
    name: 'Single Arm Push Press',
    imagePath: '/media/repdb/single-arm-push-press.webp',
    videoPath: null,
    cues: '',
    execution: '',
  },
];

export const sessions: Session[] = [
  {
    id: 'session-2026-10-07',
    title: 'WOD October 7',
    trainedOn: '2026-10-07',
    location: '',
    equipment: '',
    weather: '',
    athleteNote: '',
    coachNote: '',
    blocks: [
      {
        id: 'block-warmup',
        title: 'Warm-Up',
        scheme: '每一項在 1 分鐘內做完，剩下的時間休息。',
        items: [
          {
            id: 'wu-1',
            movementId: 'shoulder-taps',
            name: 'Shoulder Taps',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
          {
            id: 'wu-2',
            movementId: 'banded-pull-aparts',
            name: 'Banded Pull Aparts',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
          {
            id: 'wu-3',
            movementId: 'single-arm-row',
            name: 'Single Arm Row',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '5/5',
          },
          {
            id: 'wu-4',
            movementId: 'v-ups',
            name: 'V-Ups',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
        ],
      },
      {
        id: 'block-prep',
        title: 'Movement Prep',
        scheme: '',
        items: [
          {
            id: 'prep-1',
            movementId: 'triple-extension',
            name: 'Triple Extension',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: 'Triple extension of the ankle, knees, and hips followed by a shoulder shrug',
          },
          {
            id: 'prep-2',
            movementId: 'ascending-scarecrow-pull',
            name: 'Ascending Scarecrow Pull',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: 'Triple extension + object reaching chest level. Start small and increase height as the movement gets stronger.',
          },
          {
            id: 'prep-3',
            movementId: 'muscle-clean',
            name: 'Muscle Clean',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: 'Everything we’ve learned put together.',
          },
        ],
      },
      {
        id: 'block-emom',
        title: 'EMOM10',
        scheme: 'Every Minute on the Minute for 10 Minutes. Rest remaining of the minute.',
        items: [
          {
            id: 'emom-1',
            movementId: 'single-arm-muscle-clean',
            name: 'Single Arm Muscle Clean',
            sets: 'Sets 1-5',
            frequencyAndTime: '4 to 6',
            tempo: '',
            note: '3/3',
          },
          {
            id: 'emom-2',
            movementId: 'single-arm-push-press',
            name: 'Single Arm Push Press',
            sets: 'Sets 6-10',
            frequencyAndTime: '4 to 6',
            tempo: '',
            note: '3/3',
          },
        ],
      },
    ],
  },
];
