import type { Movement, Session } from '@app/contracts';

export const sessionOverviews: Readonly<Record<string, string>> = {
  'session-2026-10-07': '/media/session-2026-10-07.jpg',
};

export const movements: Movement[] = [
  {
    id: 'shoulder-taps',
    name: 'Shoulder Taps 平板撐碰肩',
    imagePath: '/media/shoulder-taps.jpg',
    videoPath: null,
    cues: '① 雙手撐地，身體保持一直線。② 單手碰對側肩膀，左右交替。③ 核心收緊，避免骨盆左右晃動。',
    execution: '',
  },
  {
    id: 'banded-pull-aparts',
    name: 'Banded Pull Aparts 彈力帶水平拉開',
    imagePath: '/media/repdb/banded-pull-aparts.webp',
    videoPath: null,
    cues: '① 雙手向前伸直，握住彈力帶。② 肩胛骨向後收，將彈力帶向兩側拉開。③ 肩膀放鬆，避免聳肩或拱腰。',
    execution: '',
  },
  {
    id: 'single-arm-row',
    name: 'Single Arm Row 單臂划船',
    imagePath: '/media/repdb/single-arm-row.webp',
    videoPath: null,
    cues: '① 髖部後推，背部保持自然平直。② 手肘沿身體側邊向後拉。③ 緩慢放下重量，避免軀幹旋轉。',
    execution: '',
  },
  {
    id: 'v-ups',
    name: 'V-Ups V 字捲腹',
    imagePath: '/media/repdb/v-ups.webp',
    videoPath: null,
    cues: '① 仰躺，雙手向頭頂延伸。② 同時抬起上半身與雙腿，形成 V 字。③ 核心控制動作，避免甩動借力。',
    execution: '',
  },
  {
    id: 'triple-extension',
    name: 'Triple Extension 三重伸展',
    imagePath: '/media/prep/triple-extension.jpg',
    videoPath: null,
    cues: '1. 髖部後推、膝蓋微彎，保持背部自然平直。\n2. 快速伸直腳踝、膝蓋與髖部，向上發力。\n3. 最後順勢聳肩，保持手臂放鬆。',
    execution: '',
  },
  {
    id: 'ascending-scarecrow-pull',
    name: 'Ascending Scarecrow Pull 漸進式高拉',
    imagePath: '/media/prep/ascending-scarecrow-pull.jpg',
    videoPath: null,
    cues: '1. 從髖部後推、膝蓋微彎的姿勢開始。\n2. 利用三重伸展帶動重量向上，手肘向上、向外提起。\n3. 從較低高度開始，逐漸拉至胸口高度，避免只靠手臂出力。',
    execution: '',
  },
  {
    id: 'muscle-clean',
    name: 'Muscle Clean 肌力上膊',
    imagePath: '/media/prep/muscle-clean.jpg',
    videoPath: null,
    cues: '1. 髖部後推、膝蓋微彎，重量靠近身體。\n2. 利用三重伸展與聳肩，帶動重量快速向上。\n3. 手肘迅速轉至重量下方，將重量接至肩膀前側的架式位置（Rack Position）。\n4. 站穩並控制重量，避免用手臂硬拉或讓重量撞擊身體。',
    execution: '',
  },
  {
    id: 'single-arm-muscle-clean',
    name: 'Single Arm Muscle Clean 單臂肌力上膊',
    imagePath: '/media/single-arm-muscle-clean.jpg',
    videoPath: null,
    cues: '',
    execution: '',
  },
  {
    id: 'single-arm-push-press',
    name: 'Single Arm Push Press 單臂借力推舉',
    imagePath: '/media/single-arm-push-press.jpg',
    videoPath: null,
    cues: '',
    execution: '',
  },
];

export const sessions: Session[] = [
  {
    id: 'session-2026-10-07',
    title: 'Work-Out Diary',
    trainedOn: '2026-10-07',
    location: '',
    equipment: '',
    weather: '',
    athleteNote: '',
    coachNote: '',
    blocks: [
      {
        id: 'block-warmup',
        title: 'Warm-Up 暖身',
        scheme: '每一項在 1 分鐘內做完，剩下的時間休息。',
        items: [
          {
            id: 'wu-1',
            movementId: 'shoulder-taps',
            name: 'Shoulder Taps',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
          {
            id: 'wu-2',
            movementId: 'banded-pull-aparts',
            name: 'Banded Pull Aparts',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
          {
            id: 'wu-3',
            movementId: 'single-arm-row',
            name: 'Single Arm Row',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '5/5',
          },
          {
            id: 'wu-4',
            movementId: 'v-ups',
            name: 'V-Ups',
            sets: '',
            frequencyAndTime: '40 秒，休息 20 秒',
            tempo: '',
            note: '',
          },
        ],
      },
      {
        id: 'block-prep',
        title: 'Movement Prep 主要訓練',
        scheme: '',
        items: [
          {
            id: 'prep-1',
            movementId: 'triple-extension',
            name: 'Triple Extension 三重伸展',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: '',
          },
          {
            id: 'prep-2',
            movementId: 'ascending-scarecrow-pull',
            name: 'Ascending Scarecrow Pull 漸進式高拉',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: '',
          },
          {
            id: 'prep-3',
            movementId: 'muscle-clean',
            name: 'Muscle Clean 肌力上膊',
            sets: '',
            frequencyAndTime: '',
            tempo: '',
            note: '',
          },
        ],
      },
      {
        id: 'block-emom',
        title: 'EMOM10 循環頻率',
        scheme: 'Every Minute on the Minute for 10 Minutes. Rest remaining of the minute.',
        items: [
          {
            id: 'emom-1',
            movementId: 'single-arm-muscle-clean',
            name: 'Single Arm Muscle Clean',
            sets: 'Sets 1-5',
            frequencyAndTime: '4 to 6',
            tempo: '',
            note: '3/3',
          },
          {
            id: 'emom-2',
            movementId: 'single-arm-push-press',
            name: 'Single Arm Push Press',
            sets: 'Sets 6-10',
            frequencyAndTime: '4 to 6',
            tempo: '',
            note: '3/3',
          },
        ],
      },
    ],
  },
];
